[game]
	name = "tutorial"
	fastmode = false
	[[game.robot]]
		file = "r"
		name = "robot"
	[[game.camera_position]]
		robot = "robot"
		x_cam = 0.5
		y_cam = 0
		z_cam = 0.6
		p_cam = 0
		q_cam = 0
		r_cam = 3.14
